package gzb.db.pay_system.dao;
import gzb.db.pay_system.entity.PsAdmin;
import gzb.db.pay_system.entity.PsApp;
import gzb.db.pay_system.entity.PsDev;
import gzb.db.pay_system.entity.PsOrder;
import gzb.db.pay_system.entity.PsUser;
import gzb.tools.ListPage;
import java.util.List;
public interface BaseDao {
    PsAdmin psAdminFind(Long psAdminId);
    PsAdmin psAdminFind(String sql, Object[] arr);
    PsAdmin psAdminFind(PsAdmin psAdmin);
    PsAdmin psAdminFindCache(Long ps_admin_id,int mm);
    PsAdmin psAdminFindCache(String sql, Object[] arr,int mm);
    PsAdmin psAdminFindCache(PsAdmin psAdmin,int mm);
    List<PsAdmin> psAdminQuery(String sql, Object[] arr);
    List<PsAdmin> psAdminQuery(PsAdmin psAdmin);
    ListPage psAdminQuery(String sql, Object[] arr, int page, int limit);
    ListPage psAdminQuery(PsAdmin psAdmin, int page, int limit, int maxPage, int maxLimit);
    List<PsAdmin> psAdminQueryCache(String sql, Object[] arr, int mm);
    List<PsAdmin> psAdminQueryCache(PsAdmin psAdmin, int mm);
    ListPage psAdminQueryCache(String sql, Object[] arr, int page, int limit, int mm);
    ListPage psAdminQueryCache(PsAdmin psAdmin, int page, int limit, int maxPage, int maxLimit, int mm);
    int psAdminDelete(PsAdmin psAdmin);
    int psAdminInsert(PsAdmin psAdmin);
    int psAdminUpdate(PsAdmin psAdmin);
    int psAdminBatch(List<PsAdmin> list, boolean autoId);
    int psAdminBatch(List<PsAdmin> list);
    int psAdminBatch(String sql, List<Object[]> list);
    int psAdminInsertAsy(PsAdmin psAdmin, boolean auto);
    int psAdminInsertAsy(PsAdmin psAdmin);
    int psAdminDeleteAsy(PsAdmin psAdmin);
    int psAdminUpdateAsy(PsAdmin psAdmin);
    PsApp psAppFind(Long psAppId);
    PsApp psAppFind(String sql, Object[] arr);
    PsApp psAppFind(PsApp psApp);
    PsApp psAppFindCache(Long ps_app_id,int mm);
    PsApp psAppFindCache(String sql, Object[] arr,int mm);
    PsApp psAppFindCache(PsApp psApp,int mm);
    List<PsApp> psAppQuery(String sql, Object[] arr);
    List<PsApp> psAppQuery(PsApp psApp);
    ListPage psAppQuery(String sql, Object[] arr, int page, int limit);
    ListPage psAppQuery(PsApp psApp, int page, int limit, int maxPage, int maxLimit);
    List<PsApp> psAppQueryCache(String sql, Object[] arr, int mm);
    List<PsApp> psAppQueryCache(PsApp psApp, int mm);
    ListPage psAppQueryCache(String sql, Object[] arr, int page, int limit, int mm);
    ListPage psAppQueryCache(PsApp psApp, int page, int limit, int maxPage, int maxLimit, int mm);
    int psAppDelete(PsApp psApp);
    int psAppInsert(PsApp psApp);
    int psAppUpdate(PsApp psApp);
    int psAppBatch(List<PsApp> list, boolean autoId);
    int psAppBatch(List<PsApp> list);
    int psAppBatch(String sql, List<Object[]> list);
    int psAppInsertAsy(PsApp psApp, boolean auto);
    int psAppInsertAsy(PsApp psApp);
    int psAppDeleteAsy(PsApp psApp);
    int psAppUpdateAsy(PsApp psApp);
    PsDev psDevFind(Long psDevId);
    PsDev psDevFind(String sql, Object[] arr);
    PsDev psDevFind(PsDev psDev);
    PsDev psDevFindCache(Long ps_dev_id,int mm);
    PsDev psDevFindCache(String sql, Object[] arr,int mm);
    PsDev psDevFindCache(PsDev psDev,int mm);
    List<PsDev> psDevQuery(String sql, Object[] arr);
    List<PsDev> psDevQuery(PsDev psDev);
    ListPage psDevQuery(String sql, Object[] arr, int page, int limit);
    ListPage psDevQuery(PsDev psDev, int page, int limit, int maxPage, int maxLimit);
    List<PsDev> psDevQueryCache(String sql, Object[] arr, int mm);
    List<PsDev> psDevQueryCache(PsDev psDev, int mm);
    ListPage psDevQueryCache(String sql, Object[] arr, int page, int limit, int mm);
    ListPage psDevQueryCache(PsDev psDev, int page, int limit, int maxPage, int maxLimit, int mm);
    int psDevDelete(PsDev psDev);
    int psDevInsert(PsDev psDev);
    int psDevUpdate(PsDev psDev);
    int psDevBatch(List<PsDev> list, boolean autoId);
    int psDevBatch(List<PsDev> list);
    int psDevBatch(String sql, List<Object[]> list);
    int psDevInsertAsy(PsDev psDev, boolean auto);
    int psDevInsertAsy(PsDev psDev);
    int psDevDeleteAsy(PsDev psDev);
    int psDevUpdateAsy(PsDev psDev);
    PsOrder psOrderFind(Long psOrderId);
    PsOrder psOrderFind(String sql, Object[] arr);
    PsOrder psOrderFind(PsOrder psOrder);
    PsOrder psOrderFindCache(Long ps_order_id,int mm);
    PsOrder psOrderFindCache(String sql, Object[] arr,int mm);
    PsOrder psOrderFindCache(PsOrder psOrder,int mm);
    List<PsOrder> psOrderQuery(String sql, Object[] arr);
    List<PsOrder> psOrderQuery(PsOrder psOrder);
    ListPage psOrderQuery(String sql, Object[] arr, int page, int limit);
    ListPage psOrderQuery(PsOrder psOrder, int page, int limit, int maxPage, int maxLimit);
    List<PsOrder> psOrderQueryCache(String sql, Object[] arr, int mm);
    List<PsOrder> psOrderQueryCache(PsOrder psOrder, int mm);
    ListPage psOrderQueryCache(String sql, Object[] arr, int page, int limit, int mm);
    ListPage psOrderQueryCache(PsOrder psOrder, int page, int limit, int maxPage, int maxLimit, int mm);
    int psOrderDelete(PsOrder psOrder);
    int psOrderInsert(PsOrder psOrder);
    int psOrderUpdate(PsOrder psOrder);
    int psOrderBatch(List<PsOrder> list, boolean autoId);
    int psOrderBatch(List<PsOrder> list);
    int psOrderBatch(String sql, List<Object[]> list);
    int psOrderInsertAsy(PsOrder psOrder, boolean auto);
    int psOrderInsertAsy(PsOrder psOrder);
    int psOrderDeleteAsy(PsOrder psOrder);
    int psOrderUpdateAsy(PsOrder psOrder);
    PsUser psUserFind(Long psUserId);
    PsUser psUserFind(String sql, Object[] arr);
    PsUser psUserFind(PsUser psUser);
    PsUser psUserFindCache(Long ps_user_id,int mm);
    PsUser psUserFindCache(String sql, Object[] arr,int mm);
    PsUser psUserFindCache(PsUser psUser,int mm);
    List<PsUser> psUserQuery(String sql, Object[] arr);
    List<PsUser> psUserQuery(PsUser psUser);
    ListPage psUserQuery(String sql, Object[] arr, int page, int limit);
    ListPage psUserQuery(PsUser psUser, int page, int limit, int maxPage, int maxLimit);
    List<PsUser> psUserQueryCache(String sql, Object[] arr, int mm);
    List<PsUser> psUserQueryCache(PsUser psUser, int mm);
    ListPage psUserQueryCache(String sql, Object[] arr, int page, int limit, int mm);
    ListPage psUserQueryCache(PsUser psUser, int page, int limit, int maxPage, int maxLimit, int mm);
    int psUserDelete(PsUser psUser);
    int psUserInsert(PsUser psUser);
    int psUserUpdate(PsUser psUser);
    int psUserBatch(List<PsUser> list, boolean autoId);
    int psUserBatch(List<PsUser> list);
    int psUserBatch(String sql, List<Object[]> list);
    int psUserInsertAsy(PsUser psUser, boolean auto);
    int psUserInsertAsy(PsUser psUser);
    int psUserDeleteAsy(PsUser psUser);
    int psUserUpdateAsy(PsUser psUser);

}